a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
o = input("Choose operation (+, -, *, /): ")
if o == "+" : print(a+b)
if o == "-" : print(a-b)
if o == "*" : print(a*b)
if o == "/" : print(a/b)
